---
ABIS_REPOSITORIES:
  - NAME: 'dermalog-abis'
    DESCRIPTION: "ABIS yum repo {{ ABIS_VERSION }}"
    REPO_BASEURL: "file:///opt/dermalog/install/abis/{{ ABIS_VERSION }}/rpms/el{{ ansible_distribution_major_version }}/"
    SSLVERIFY: false

ABIS_COMMON_FLAVOUR: 'WEBABIS_CIVIL'

WIBU_SERVER:
  - 10.120.20.206
ABSENT_SERVERS:
  - 255.255.255.255

DB_SERVER: 'cde0969'
DB_ABIS_SERVICE: 'orclpdb1'
DB_VARIANT: 'oracle'
DB_SYSTEM_USER: 'system'
DB_SYSTEM_PWD: 'oracle'
BIOMETRIC_STORE_DB_PWD: 'biometricstore'
WEB_ABIS_DB_PWD: 'webabis'

ABIS_DISPATCHER_SNMP_ENABLE: true

DB_DATASOURCE_URL: "jdbc:oracle:thin:@//{{ DB_SERVER }}/{{ DB_ABIS_SERVICE }}"
DB_TABLESPACE_TABLES: 'DATASTORE'
DB_TABLESPACE_INDICES: 'DATASTORE_IDX'
DB_TABLESPACE_LOB: 'DATASTORE_LOB'

BIOMETRIC_STORE_DB_VARIANT: "{{ DB_VARIANT }}"
BIOMETRIC_STORE_DATASOURCE_URL: "{{ DB_DATASOURCE_URL }}"
BIOMETRIC_STORE_DB_USERNAME: 'BIOMETRICSTORE'

WEB_ABIS_DB_VARIANT: "{{ DB_VARIANT }}"
WEB_ABIS_DATASOURCE_URL: "{{ DB_DATASOURCE_URL }}"
WEB_ABIS_DB_USERNAME: 'WEBABIS'
WEB_ABIS_CORS_ALLOWED_ORIGINS: '*'

WEB_ABIS_FRONTEND_PAGE_PERMISSIONS: ['demo', 'identity', 'match']
WEB_ABIS_FRONTEND_WEB_ABIS_DATASOURCE_URL: "{{ WEB_ABIS_DATASOURCE_URL }}"
WEB_ABIS_FRONTEND_WEB_ABIS_DB_VARIANT: "{{ WEB_ABIS_DB_VARIANT }}"
WEB_ABIS_FRONTEND_WEB_ABIS_DB_USERNAME: "{{ WEB_ABIS_DB_USERNAME }}"
WEB_ABIS_FRONTEND_WEB_ABIS_DB_PWD: "{{ WEB_ABIS_DB_PWD }}"

ABIS_DB_MIGRATION_EXEC_MIGRATIONS:
  - service_type: 'biometric-store'
    db_variant: "{{ DB_VARIANT }}"
    db_jdbc_url: "{{ BIOMETRIC_STORE_DATASOURCE_URL }}"
    db_system_user: "{{ DB_SYSTEM_USER }}"
    db_system_pwd: "{{ DB_SYSTEM_PWD }}"
    db_schema: "{{ BIOMETRIC_STORE_DB_USERNAME }}"
    tablespace_tables: "{{ DB_TABLESPACE_TABLES }}"
    tablespace_indices: "{{ DB_TABLESPACE_INDICES }}"
    tablespace_lob: "{{ DB_TABLESPACE_LOB }}"
  - service_type: 'web-abis'
    db_variant: "{{ DB_VARIANT }}"
    db_jdbc_url: "{{ WEB_ABIS_DATASOURCE_URL }}"
    db_system_user: "{{ DB_SYSTEM_USER }}"
    db_system_pwd: "{{ DB_SYSTEM_PWD }}"
    db_schema: "{{ WEB_ABIS_DB_USERNAME }}"
    tablespace_tables: "{{ DB_TABLESPACE_TABLES }}"
    tablespace_indices: "{{ DB_TABLESPACE_INDICES }}"
    tablespace_lob: "{{ DB_TABLESPACE_LOB }}"

SCHEMAS:
  - SCHEMA: "{{ BIOMETRIC_STORE_DB_USERNAME }}"
    PASSWORD: "{{ BIOMETRIC_STORE_DB_PWD }}"
    DEFAULT_TABLESPACE: "{{ DB_TABLESPACE_TABLES }}"
    TABLESPACES:
      - "{{ DB_TABLESPACE_TABLES }}"
      - "{{ DB_TABLESPACE_INDICES }}"
      - "{{ DB_TABLESPACE_LOB }}"
  - SCHEMA: "{{ WEB_ABIS_DB_USERNAME }}"
    PASSWORD: "{{ WEB_ABIS_DB_PWD }}"
    DEFAULT_TABLESPACE: "{{ DB_TABLESPACE_TABLES }}"
    TABLESPACES:
      - "{{ DB_TABLESPACE_TABLES }}"
      - "{{ DB_TABLESPACE_INDICES }}"
      - "{{ DB_TABLESPACE_LOB }}"

SNMP_SNMPD_CONFIG:
  - 'agentXPerms 664 777 dermalog dermalog'
  - 'rocommunity public 127.0.0.1 .1.3.6.1.4.1.39157'
